import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import Footer from '@/layouts/Footer'
import NavBar from '@/layouts/NavBar/NavBar'

import Favicon from '@/public/favicon.ico';
import RootContainer from '@/layouts/RootContainer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Crypto Search',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: Favicon.src }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${montserrat.className} min-h-screen
                        grid grid-rows-[auto,1fr,auto] leading-loose tracking-wide bg-zinc-50`}
      >
          <RootContainer>
            <NavBar/>
            <main className="w-full max-w-7xl mx-auto py-16 px-6 md:px-8 2xl:px-0">
              {children}
            </main>
            <Footer />
          </RootContainer>
      </body>
    </html>
  )
}
